### ISSUE TITLE
Blank page issue

### ISSUE THREAD

**Issue by memotiur** [niklasravnsborg/laravel-pdf#147]
After using this library I got a blank page as output.

**Comment by niklasravnsborg** [comment]
Hi @memotiur Please use this template to report your issue: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Use this method '...'
2. Download PDF '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by Malkom** [comment]
I have the same issue.

**Describe the bug**
The output PDF is a blank document of 250 pages O_o

**The solution for me :** 
In my view, I have a link to css stylesheet : 
<link rel="stylesheet" href="{{ asset('/css/app.css') }}">

I have comment this line and my PDF is ok but it have not CSS of my laravel app.
I have to see mpdf doc to apply CSS : [Mpdf Doc](https://mpdf.github.io/css-stylesheets/introduction.html)

**Comment by Malkom** [comment]
Finaly, I can't apply my CSS on the PDF with the config file or with a call in my view like that : 
` <link rel="stylesheet" href="/public/css/app.css">`

Any idea ?

**Comment by rizwanIttihad** [comment]
I am having the same issue when I remove css files then the pdf is generated with all the content without css and if I include css it generates 1470 blank pages.

**Comment by niklasravnsborg** [comment]
Mpdf requires all styling to be inside of the document, either inline or using the style tag. <link> is not supported, afaik.
