### ISSUE TITLE
file size not reducing after removing niklasravnsborg/laravel-pdf generated pdf pages in windows

### ISSUE THREAD

**Issue by syamlalkollam** [niklasravnsborg/laravel-pdf#149]
I'm using niklasravnsborg/laravel-pdf for converting html page to pdf format with laravel blade. i set Calibri as my default font.if i remove some pages from generated pdf document, total file size not reducing on windows. but still reducing on mac.

**Comment by niklasravnsborg** [comment]
Hi please submit your bug report in the following format:

We are only able to handle bug reports at this point in time. If you have an idea on how to improve the library, please submit a pull request.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Use this method '...'
2. Download PDF '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by syamlalkollam** [comment]
**Bug Description**
I'm using niklasravnsborg/laravel-pdf for converting html page to pdf format with laravel blade. sometimes i need remove some particular pages from pdf. i remove some pages from pdf file, but pdf size not reducing as proportionally.
for example: i have 31MB generated pdf file with 675 pages . i removed 676 pages and saved, but now pdf size is 30 MB. not reducing size as proportional. remaining page contain only text.
but file size is bigger.

pdf generating code
```
$mpdf = PDF::loadView('report.reportpdf',[table_data'=>$table_data]);
return $mpdf->download($_filename);
```
**Expected behavior**
pdf file size should decrease after removing pages 
![Screen Shot 2019-11-27 at 10 18 10 AM](https://user-images.githubusercontent.com/47673338/69698644-5828df80-10ff-11ea-9381-b48e128f01ec.png)
