### ISSUE TITLE
Non numerica value encountered

### ISSUE THREAD

**Issue by sdkcodes** [niklasravnsborg/laravel-pdf#52]
After upgrading my php version to 7.1, when I try to generate pdf, it generates a *non numeric value encountered* error.
Could this be a problem with the version?

**Comment by erfansahaf** [comment]
First of all, it's not an error, it's just a warning that is caused by main `mdpf` library. This warning occurs when the developer wants to do calculations on strings and numeric values in PHP 7.1.
I guess you used `auto` margin which will be the reason of getting this warning.
Check [this issue](https://github.com/mpdf/mpdf/issues/302) for more information and also the solutions.

**Comment by niklasravnsborg** [comment]
@sdkcodes Did this solve the problem for you? Thanks @erfansahaf. 👍 

Will close this for now...
